version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: zenuxs-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: zenuxs-desigen

  server:
    build: .
    container_name: zenuxs-backend-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/zenuxs-desigen
    depends_on:
      - mongodb

volumes:
  mongo_data:
